/**
 * Alix Design System — token build.
 *
 * tokens/*.json (W3C/DTCG, the source of truth)  ──►  Style Dictionary  ──┬─►  platform/native/tokens.ts   (the app consumes this)
 *                                                                          ├─►  export/build/tokens.figma.json     (Tokens Studio import)
 *                                                                          └─►  export/build/variables.figma.json  (Figma Variables API scaffold)
 *
 * One-way: tokens flow OUT. Nothing here is hand-edited downstream — change tokens/ and re-run.
 *   npm run build:tokens   → native only
 *   npm run export:figma   → figma only
 *   npm run build          → both
 */
import StyleDictionary from 'style-dictionary';

/* ---------- helpers ---------- */

// Resolved value of a token (DTCG: SD resolves refs into `.value`, keeps original `$value`).
const valueOf = (t) => (t.value !== undefined ? t.value : t.$value);
const typeOf = (t) => t.type || t.$type;

// camelCase a token path segment ("on-dark-secondary" → "onDarkSecondary", "1" → "1").
const camel = (s) => String(s).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

// rgba(r,g,b,a) → { color: "#rrggbb", opacity: a }; passthrough for other formats.
function splitRgba(str) {
  const m = /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/.exec(String(str));
  if (!m) return { color: str, opacity: 1 };
  const hex = '#' + [m[1], m[2], m[3]].map((n) => Number(n).toString(16).padStart(2, '0')).join('');
  return { color: hex, opacity: m[4] !== undefined ? Number(m[4]) : 1 };
}

// A DTCG shadow value → an RN-ready shadow object (+ Android elevation).
function toRNShadow(v) {
  const { color, opacity } = splitRgba(v.color);
  return {
    shadowColor: color,
    shadowOffset: { width: v.offsetX ?? 0, height: v.offsetY ?? 0 },
    shadowOpacity: opacity,
    shadowRadius: v.blur ?? 0,
    elevation: Math.round(v.offsetY ?? (v.blur ?? 0) / 4),
  };
}

// Transform one token's resolved value into its RN runtime shape.
function nativeValue(t) {
  const v = valueOf(t);
  if (typeOf(t) === 'shadow') return toRNShadow(v);
  return v; // numbers stay numbers, colors/families stay strings, typography/cubicBezier stay as-is
}

// Build a nested object from a flat token list, keyed by camelCased path, via `pick(token)`.
function nest(tokens, pick) {
  const root = {};
  for (const t of tokens) {
    let node = root;
    const path = t.path;
    path.forEach((seg, i) => {
      const key = camel(seg);
      if (i === path.length - 1) node[key] = pick(t);
      else node = node[key] ??= {};
    });
  }
  return root;
}

const stamp = (cmd) =>
  `/**\n * GENERATED by \`${cmd}\` from tokens/*.json — DO NOT EDIT BY HAND.\n * Edit the token source and re-run the build. See export/build-tokens.js.\n */\n`;

/* ---------- formats ---------- */

StyleDictionary.registerFormat({
  name: 'alix/native-ts',
  format: ({ dictionary }) => {
    const tree = nest(dictionary.allTokens, nativeValue);
    return (
      stamp('npm run build:tokens') +
      '\nexport const tokens = ' +
      JSON.stringify(tree, null, 2) +
      ' as const;\n\nexport type Tokens = typeof tokens;\nexport default tokens;\n'
    );
  },
});

// Resolved W3C/DTCG tree — Tokens Studio imports this to get our foundations.
StyleDictionary.registerFormat({
  name: 'alix/figma-tokens-studio',
  format: ({ dictionary }) => {
    const tree = {};
    for (const t of dictionary.allTokens) {
      let node = tree;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) node[seg] = { $type: typeOf(t), $value: valueOf(t) };
        else node = node[seg] ??= {};
      });
    }
    return JSON.stringify(tree, null, 2) + '\n';
  },
});

// Figma Variables REST API scaffold (color + number variables, single "Light" mode).
StyleDictionary.registerFormat({
  name: 'alix/figma-variables',
  format: ({ dictionary }) => {
    const kind = { color: 'COLOR', dimension: 'FLOAT', number: 'FLOAT', duration: 'FLOAT' };
    const variables = dictionary.allTokens
      .filter((t) => kind[typeOf(t)])
      .map((t) => ({
        name: t.path.join('/'),
        resolvedType: kind[typeOf(t)],
        valuesByMode: { Light: valueOf(t) },
      }));
    return JSON.stringify(
      { collections: [{ name: 'Alix Foundations', modes: ['Light'], variables }] },
      null,
      2,
    ) + '\n';
  },
});

/* ---------- platforms ---------- */

const config = {
  source: ['tokens/**/*.json'],
  platforms: {
    native: {
      transforms: ['name/camel'], // unique token names (silences default last-segment collisions)
      buildPath: 'platform/native/',
      files: [{ destination: 'tokens.ts', format: 'alix/native-ts' }],
    },
    figma: {
      transforms: ['name/camel'],
      buildPath: 'export/build/',
      files: [
        { destination: 'tokens.figma.json', format: 'alix/figma-tokens-studio' },
        { destination: 'variables.figma.json', format: 'alix/figma-variables' },
      ],
    },
  },
};

const target = process.argv[2] || 'all';
const sd = new StyleDictionary(config);
const platforms = target === 'all' ? ['native', 'figma'] : [target];
for (const p of platforms) {
  if (!config.platforms[p]) throw new Error(`Unknown target "${p}". Use: native | figma | all`);
  await sd.buildPlatform(p);
}
console.log(`✓ built: ${platforms.join(', ')}`);
