/**
 * GENERATED by `npm run build:tokens` from tokens/*.json — DO NOT EDIT BY HAND.
 * Edit the token source and re-run the build. See export/build-tokens.js.
 */

export const tokens = {
  "color": {
    "palette": {
      "navy": "#0C2553",
      "navyDeep": "#0E2D66",
      "white": "#FFFFFF",
      "tan": "#F4F3F1",
      "tanDark": "#EAE8E1",
      "purple": "#B6ABFD",
      "lightBlue": "#D7F5F9",
      "symbolBlue": "#A0DAE0",
      "blue": "#1170DB",
      "ctaBlue": "#043CA5",
      "ink": "#1D1A18",
      "textWorking": "#2F3136",
      "gray": "#9E9E9E",
      "red": "#B23A2B",
      "redSoft": "#F6E7E4",
      "amber": "#A56A12",
      "amberSoft": "#F7EEDD",
      "green": "#2F6B4F",
      "greenSoft": "#E4EEE8",
      "blueSoft": "#E4F0FB",
      "vizGreen": "#15A573",
      "teal": "#05D3BD",
      "cyan": "#72F2E4",
      "yellow": "#FFEB67",
      "orange": "#FFC167"
    },
    "bg": {
      "default": "#FFFFFF",
      "alt": "#F4F3F1",
      "block": "#EAE8E1",
      "dark": "#0C2553",
      "scrim": "rgba(29,26,24,0.4)"
    },
    "fg": {
      "default": "#1D1A18",
      "secondary": "#2F3136",
      "muted": "#9E9E9E",
      "brand": "#0C2553",
      "onDark": "#FFFFFF",
      "onDarkSecondary": "#D7F5F9"
    },
    "accent": {
      "default": "#B6ABFD",
      "soft": "#D7F5F9",
      "onAccent": "#1D1A18"
    },
    "action": {
      "default": "#1170DB",
      "press": "#043CA5"
    },
    "border": {
      "hairline": "rgba(29,26,24,0.12)"
    },
    "viz": {
      "series1": "#0C2553",
      "series2": "#B6ABFD",
      "series3": "#15A573",
      "series4": "#05D3BD",
      "series5": "#FFC167",
      "series6": "#72F2E4",
      "series7": "#FFEB67",
      "grid": "#EAE8E1"
    },
    "state": {
      "error": {
        "strong": "#B23A2B",
        "soft": "#F6E7E4"
      },
      "warning": {
        "strong": "#A56A12",
        "soft": "#F7EEDD"
      },
      "success": {
        "strong": "#2F6B4F",
        "soft": "#E4EEE8"
      },
      "info": {
        "strong": "#1170DB",
        "soft": "#E4F0FB"
      }
    }
  },
  "shadow": {
    "sm": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowOpacity": 0.05,
      "shadowRadius": 2,
      "elevation": 1
    },
    "md": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 4
      },
      "shadowOpacity": 0.06,
      "shadowRadius": 16,
      "elevation": 4
    },
    "lg": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowOpacity": 0.08,
      "shadowRadius": 40,
      "elevation": 12
    },
    "overlay": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowOpacity": 0.12,
      "shadowRadius": 40,
      "elevation": 12
    },
    "fab": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowOpacity": 0.18,
      "shadowRadius": 40,
      "elevation": 12
    }
  },
  "duration": {
    "fast": 120,
    "base": 180,
    "slow": 260
  },
  "easing": {
    "default": [
      0.2,
      0.8,
      0.2,
      1
    ]
  },
  "radius": {
    "sm": 8,
    "md": 12,
    "lg": 26,
    "xl": 36,
    "pill": 999
  },
  "shape": {
    "sheer": {
      "angle": 20,
      "inset": 14,
      "overlap": 2
    },
    "container": {
      "radiusRatio": 0.03,
      "radiusMin": 8,
      "radiusMax": 28,
      "gridColumns": 12,
      "gridRows": 16,
      "tabColumns": 4,
      "tabPadding": 14
    },
    "card": {
      "marginRatio": 0.1,
      "marginRatioTight": 0.18,
      "radiusRatio": 0.08,
      "radiusMin": 12,
      "radiusMax": 32
    }
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 24,
    "6": 32,
    "7": 48,
    "8": 64,
    "9": 96
  },
  "font": {
    "family": {
      "display": "MakeWay-Regular",
      "displayApp": "MakeWayApp-Regular",
      "sans": "BeausiteClassic-Regular",
      "sansMedium": "BeausiteClassic-Medium",
      "sansSemibold": "BeausiteClassic-Semibold",
      "sansApp": "BeausiteClassicApp-Regular",
      "sansAppMedium": "BeausiteClassicApp-Medium",
      "sansAppSemibold": "BeausiteClassicApp-Semibold"
    }
  },
  "text": {
    "display": {
      "fontFamily": "MakeWay-Regular",
      "fontSize": 34,
      "lineHeight": 37,
      "letterSpacing": -0.68
    },
    "title": {
      "fontFamily": "MakeWay-Regular",
      "fontSize": 28,
      "lineHeight": 31,
      "letterSpacing": -0.56
    },
    "headline": {
      "fontFamily": "MakeWay-Regular",
      "fontSize": 22,
      "lineHeight": 24,
      "letterSpacing": -0.44
    },
    "numeral": {
      "fontFamily": "MakeWay-Regular",
      "fontSize": 28,
      "lineHeight": 31,
      "letterSpacing": 0
    },
    "lead": {
      "fontFamily": "BeausiteClassic-Regular",
      "fontSize": 20,
      "lineHeight": 26,
      "letterSpacing": 0
    },
    "body": {
      "fontFamily": "BeausiteClassic-Regular",
      "fontSize": 16,
      "lineHeight": 21,
      "letterSpacing": 0
    },
    "bodyStrong": {
      "fontFamily": "BeausiteClassic-Semibold",
      "fontSize": 16,
      "lineHeight": 21,
      "letterSpacing": 0
    },
    "secondary": {
      "fontFamily": "BeausiteClassic-Regular",
      "fontSize": 14,
      "lineHeight": 18,
      "letterSpacing": 0
    },
    "small": {
      "fontFamily": "BeausiteClassic-Regular",
      "fontSize": 12,
      "lineHeight": 16,
      "letterSpacing": 0
    },
    "section": {
      "fontFamily": "BeausiteClassic-Semibold",
      "fontSize": 17,
      "lineHeight": 22,
      "letterSpacing": 0
    },
    "eyebrow": {
      "fontFamily": "BeausiteClassic-Regular",
      "fontSize": 11,
      "lineHeight": 14,
      "letterSpacing": 0.44,
      "textTransform": "uppercase"
    },
    "button": {
      "fontFamily": "BeausiteClassic-Medium",
      "fontSize": 16,
      "lineHeight": 20,
      "letterSpacing": 0
    },
    "note": {
      "fontFamily": "BeausiteClassic-Regular",
      "fontSize": 16,
      "lineHeight": 21,
      "letterSpacing": 0,
      "fontStyle": "italic"
    }
  }
} as const;

export type Tokens = typeof tokens;
export default tokens;
